const actionTypes = Object.freeze({
  
  //user

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGIN_START: "USER_LOGIN_START",
  USER_LOGOUT_FAIL: "USER_LOGOUT_START",

 
  //4.create new user
  CREATE_NEW_USER_START: "CREATE_NEW_USER_START",
  CREATE_NEW_USER_SUCCESS: "CREATE_NEW_USER_SUCCESS",
  CREATE_NEW_USER_FAILDED: "CREATE_NEW_USER_FAILDED",
  //5.fetch all user
  FETCH_ALL_USER_START: "FETCH_ALL_USER_START",
  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILDED: "FETCH_ALL_USER_FAILDED",
  //7..delete one user
  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILD: "DELETE_USER_FAILD",
  //8.update one user
  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILD: "UPDATE_USER_FAILD",
})

export default actionTypes;
